name: Sync Financial And Data Skills

on:
  push:
    branches:
      - main

jobs:

  sync-financial-and-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@aisa.one"

      - name: Split Financial And Data folder
        run: bash .github/scripts/prepare-category-repo.sh financial

      - name: Commit and push to Financial And Data Repo
        env:
          TOKEN: ${{ secrets.SYNC_AISAS_KILLS_TOKEN  }}
        run: |
          ls -la

          git status -s
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync Financial And Data folder"
            git remote set-url origin "https://x-access-token:${TOKEN}@github.com/AISA-skills/financial-data-skills.git"
            git push origin main --force
          fi