name: Sync Search And Research Skills

on:
  push:
    branches:
      - main

jobs:

  sync-search-and-research:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout  repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@aisa.one"

      - name: Split Search And Research folder
        run: bash .github/scripts/prepare-category-repo.sh search-research

      - name: Commit and push to Search And Research Repo
        env:
          TOKEN: ${{ secrets.SYNC_AISAS_KILLS_TOKEN  }}
        run: |
          ls -la

          git status -s
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Sync Search And Research folder"
            git remote set-url origin "https://x-access-token:${TOKEN}@github.com/AISA-skills/search-research-skills.git"
            git push origin main --force
          fi